version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8001"
    volumes:
      - ./backend:/app
    ports:
      - "8055:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:copybook@db:5432/vacancy
    restart: always

  db:
    image: postgres:16
    container_name: vacancy-db
    environment:
      POSTGRES_DB: YOUR_PQL_DB
      POSTGRES_USER: YOUR_PQL_URESNAME
      POSTGRES_PASSWORD: YOUR_PQL_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend
    command: npm start  # или npm run dev для Vite

volumes:
  postgres_data:
